jenkins:
  systemMessage: "\n\nDemo setup for Jenkins Configuration as Code plugin......\n\n"

  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"  
  
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin123
         
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: true
   
  crumbIssuer: "standard"
  
  remotingSecurity:
    enabled: true
      
jobs:
  - script: >
      pipelineJob('my-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/nistalhelmuth/pipelines-sandbox.git')
                }
                branch('*/master')
              }
            }
            lightweight()
          }
        }
      }
